server:
  port: 8080

spring:
  application:
    name: order

  config:
    import: "optional:configserver:"
    name: order             # ??? ?? ?? ??
  #    profile: default     # profile ? (optional)
  cloud:
    gateway:
      routes: [ ]

  kafka:
    bootstrap-servers: localhost:9092

  datasource:
    url: jdbc:mysql://localhost:3306/ecommerce_order
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10
    jpa:
      hibernate:
        ddl-auto: none
      properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQL5InnoDBDialect  # MySQL ?? ??
    mysql:
      datasource:
        platform: MYSQL                             # ?????? ??? ??
    logging:
      level:
        org.hibernate.SQL: debug                   # Hibernate SQL ??
        org.hibernate.type.descriptor.sql.BasicBinder: trace # Hibernate ??? ??
